import type { LancementPhase } from './types.js';

export const PLAN_LANCEMENT_90J: LancementPhase[] = [
  {
    phase: 'Phase 0 — Fondations Juridiques & Accord (Semaines 1–2)',
    duree: '2 semaines',
    objectifs: [
      'Contacter routines.fr France + négocier accord de distribution exclusive Maroc',
      'Déposer trademark à l\'OMPIC (classe 3 + 35)',
      'Enregistrer domaine routines.ma (ANRT Maroc)',
      'Ouvrir compte bancaire professionnel MBF Cosmétique',
      'Déposer dossier CMI (paiement carte marocaine — délai 3–4 semaines)',
      'Identifier le transitaire douanier Casablanca',
      'Vérifier composition Longevity Complex™ (source collagène) pour conformité halal',
    ],
    responsables: ['legal', 'finance', 'coordinator'],
    livrables: [
      'Accord de distribution signé (ou en cours de négociation)',
      'Reçu dépôt OMPIC',
      'Domaine routines.ma actif',
      'Compte bancaire pro ouvert',
      'Dossier CMI déposé',
    ],
    budget: 30000,
  },
  {
    phase: 'Phase 1 — Adaptation & Conformité (Semaines 3–8)',
    duree: '6 semaines',
    objectifs: [
      'Initier les déclarations DMP Maroc (6 SKUs en parallèle)',
      'Démarrer audit halal IMANOR (3–6 mois de délai — commencer maintenant)',
      'Commander les sleeves bilingues AR/FR avec motif zellige (Print Casa)',
      'Construire le site Shopify Maroc (thème + pages essentielles + paiements)',
      'Reformuler sérum vitamine C (ajouter niacinamide 5% pour anti-taches MA)',
      'Commander SPF50 (reformulation ou sourcing externe pour l\'édition Maroc)',
      'Recruter l\'experte beauté marocaine (community + SAV WhatsApp)',
      'Réaliser tests panel 30 femmes marocaines (phototypes IV–VI)',
      'Configurer Klaviyo + séquences email (bienvenue, abandon panier, post-achat)',
    ],
    responsables: ['legal', 'produit', 'ecommerce', 'brand', 'customer'],
    livrables: [
      'Dossiers DMP déposés (x6)',
      'Audit IMANOR initié',
      'Sleeves bilingues commandés',
      'Site Shopify "Coming Soon" live avec waitlist',
      'Sérum anti-taches reformulé (batch test)',
      'Experte beauté recrutée',
    ],
    budget: 130000,
  },
  {
    phase: 'Phase 2 — Stock & Pré-Lancement (Semaines 9–11)',
    duree: '3 semaines',
    objectifs: [
      'Passer commande initiale à routines.fr France (750 unités, 6 SKUs)',
      'Transit et dédouanement (avec EUR.1, 0% droits)',
      'QC réception + apposition sleeves bilingues',
      'Envoyer 30 kits press/influenceurs nano (J-30)',
      'Publier 10 premiers contenus fondateurs (Instagram + TikTok)',
      'Activer Meta Ads test (3 000 MAD, A/B créatif "France + grade pharma" vs "anti-taches")',
      'Ouvrir la waitlist email sur le site (objectif 500+ emails avant J1)',
      'Configurer Amana COD sur Shopify',
    ],
    responsables: ['operations', 'marketing', 'brand', 'ecommerce'],
    livrables: [
      'Stock 750 unités réceptionné + sleeve apposé',
      'Kits envoyés aux 30 influenceurs',
      'Waitlist 500+ emails',
      'Amana COD + CMI fonctionnels (test commande end-to-end)',
      'ROAS test Meta > 1.8',
    ],
    budget: 80000,
  },
  {
    phase: 'Phase 3 — LANCEMENT OFFICIEL (Semaine 12)',
    duree: '1 semaine',
    objectifs: [
      'Ouvrir le shop routines.ma (J1)',
      'Email blast waitlist (-15% early-bird, code BIENVENUE)',
      'Activation simultanée des contenus influenceurs',
      'Scaler Meta Ads si ROAS > 2.5 sur le test',
      'Activer Google Ads "sérum anti-taches Maroc"',
      'Support WhatsApp actif 9h–20h sans interruption',
      'Monitoring commandes + expéditions en temps réel',
    ],
    responsables: ['coordinator', 'marketing', 'operations', 'customer'],
    livrables: [
      '200+ commandes J1–J14',
      'Zéro rupture de stock semaine 1',
      'NPS premiers retours > 65',
      'Temps réponse SAV < 2h',
    ],
    budget: 25000,
  },
  {
    phase: 'Phase 4 — Optimisation & Preuve (M2–M3)',
    duree: '6 semaines',
    objectifs: [
      'Analyser data J1–J30 : top SKUs, CAC, ROAS, CVR, profil acheteur',
      'Lancer le défi "28 jours avant/après" avec 30 clientes',
      'Activer le Quiz Peau sur le site',
      'Lancer le programme Club Routines (Smile.io)',
      'Réassort stock si sell-through > 70%',
      'Collecter 50 avis 4–5 étoiles',
      'Ouvrir la livraison France (si accord distribution inclut)',
      'Publier les résultats cliniques du panel marocain (marketing)',
    ],
    responsables: ['coordinator', 'marche', 'ecommerce', 'marketing', 'customer', 'finance'],
    livrables: [
      'Dashboard KPIs hebdomadaire actif',
      'Défi 28j en cours avec 30 participantes documentées',
      'Quiz peau live (taux capture > 9%)',
      'Club Routines lancé (50+ membres)',
      'CA cumulé M3 > 200 000 MAD',
    ],
    budget: 35000,
  },
];

export const JALONS_CRITIQUES = [
  { semaine: 1, jalon: 'Accord de distribution routines.fr France signé', bloquant: true },
  { semaine: 1, jalon: 'Dossier CMI déposé (délai 3–4 semaines)', bloquant: true },
  { semaine: 1, jalon: 'Dépôt OMPIC classe 3+35', bloquant: true },
  { semaine: 2, jalon: 'Composition Longevity Complex™ vérifiée (halal/porcin ?)', bloquant: true },
  { semaine: 3, jalon: 'Dossiers DMP déposés (6 SKUs)', bloquant: true },
  { semaine: 3, jalon: 'Audit IMANOR halal initié', bloquant: false },
  { semaine: 5, jalon: 'CMI activé sur Shopify', bloquant: true },
  { semaine: 7, jalon: 'Reformulation sérum anti-taches validée', bloquant: false },
  { semaine: 8, jalon: 'Site Shopify "Coming Soon" + waitlist active', bloquant: false },
  { semaine: 9, jalon: 'Commande stock France passée + EUR.1 demandé', bloquant: true },
  { semaine: 11, jalon: 'Stock receptionné + QC + sleeves apposés', bloquant: true },
  { semaine: 11, jalon: 'Amana COD testé end-to-end (commande réelle)', bloquant: true },
  { semaine: 11, jalon: 'Kits influenceurs envoyés (30 kits J-7)', bloquant: false },
  { semaine: 12, jalon: '🚀 LANCEMENT OFFICIEL routines.ma', bloquant: false },
  { semaine: 24, jalon: 'Certification Halal IMANOR obtenue', bloquant: false },
];

export const BUDGET_TOTAL_90J = PLAN_LANCEMENT_90J.reduce((sum, phase) => sum + phase.budget, 0);

export const RISQUES_PRINCIPAUX = [
  {
    risque: 'routines.fr France refuse ou retarde l\'accord de distribution',
    probabilite: 'Moyenne',
    impact: 'Bloquant total',
    mitigation: 'Proposer un accord test 1 an + MBF assume tous les coûts d\'adaptation + royalties 8–12%',
  },
  {
    risque: 'Longevity Complex™ contient du collagène porcin',
    probabilite: 'Faible (mais non vérifiée)',
    impact: 'Bloquant halal = perte de 65% du marché cible',
    mitigation: 'Vérifier en semaine 2. Si porcin : demander reformulation collagène marin à routines.fr, ou lancer sans cette référence.',
  },
  {
    risque: 'DMP Maroc bloque l\'importation lors du premier envoi',
    probabilite: 'Moyenne (1ère importation cosmétique)',
    impact: 'Délai 2–4 semaines + coûts stockage douanier',
    mitigation: 'Préparer dossier complet avant import. Utiliser transitaire expert cosmétiques. Obtenir toutes autorisations DMP avant envoi.',
  },
  {
    risque: 'Marché Maroc résiste au prix (350–550 MAD / sérum)',
    probabilite: 'Moyenne',
    impact: 'Ventes lentes + CAC élevé',
    mitigation: 'Kit Découverte 249 MAD = porte d\'entrée. Résultats visibles = argument de réachat. Jamais de remise sur les sérums — offrir livraison offerte plutôt.',
  },
];
